### ISSUE TITLE
New Website Articles

### ISSUE THREAD

**Issue by metagauss** [Metagauss-com/buddybot#69]
- [x] How to get OpenAI API Key #71 
- [x] How sync posts and comments data #72 
- [x] What are assistants and how to create them #73 
- [x] How to create BuddyBots and publish them on frontend #74
